#!/bin/sh
# Generate Frog/version.h from config.h + git + a local build counter.
#
#   ./scripts/stamp-version.sh            # from the Frog/ directory
#
# Runs pre-build from both CMake and Xcode. Writes two gitignored files so
# building never dirties the working tree:
#
#   version.h   the generated header the UI reads (ui/FrogVersion.h)
#   .buildnum   the local monotonic compile counter
#
# version.h is optional at compile time — FrogVersion.h pulls it in behind
# __has_include and falls back to zeros — so a fresh clone builds before this
# script has ever run.
#
# The counter debounces: one Xcode "Build" fans out across several targets
# and would otherwise bump it once per target, so stamps inside DEBOUNCE
# seconds of each other count as one build.

set -u
cd "$(dirname "$0")/.." || exit 1

DEBOUNCE=20
OUT=version.h
NUMF=.buildnum

# --- version, from config.h (the source of truth; MINOR = F-number) --------
VER=$(sed -n 's/^#define PLUG_VERSION_STR "\(.*\)"/\1/p' config.h)
[ -n "$VER" ] || VER="0.0.0"

# --- git identity -----------------------------------------------------------
if git rev-parse --git-dir >/dev/null 2>&1; then
	COMMITS=$(git rev-list --count HEAD 2>/dev/null || echo 0)
	SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
	if [ -n "$(git status --porcelain --untracked-files=no 2>/dev/null)" ]; then
		DIRTY=1
	else
		DIRTY=0
	fi
	BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)
else
	COMMITS=0; SHA=nogit; DIRTY=0; BRANCH=nogit
fi

# --- local build counter, debounced ----------------------------------------
NOW=$(date +%s)
PREV_N=0
PREV_T=0
if [ -f "$NUMF" ]; then
	PREV_N=$(sed -n '1p' "$NUMF" 2>/dev/null)
	PREV_T=$(sed -n '2p' "$NUMF" 2>/dev/null)
	case "$PREV_N" in ''|*[!0-9]*) PREV_N=0 ;; esac
	case "$PREV_T" in ''|*[!0-9]*) PREV_T=0 ;; esac
fi
if [ "$((NOW - PREV_T))" -ge "$DEBOUNCE" ]; then
	BUILD=$((PREV_N + 1))
	printf '%s\n%s\n' "$BUILD" "$NOW" > "$NUMF"
else
	BUILD=$PREV_N
	[ "$BUILD" -gt 0 ] || BUILD=1
fi

STAMP=$(date '+%Y-%m-%d %H:%M')
if [ "$DIRTY" = "1" ]; then MARK="*"; else MARK=""; fi

SHORT="$VER  b$COMMITS.$SHA$MARK"
FULL="Frog $VER — build $BUILD — $BRANCH @ $SHA$MARK — commit $COMMITS — $STAMP"

NEW=$(cat <<EOF
// Generated by scripts/stamp-version.sh — do not edit, do not commit.
#pragma once
#define FROG_VERSION_STR    "$VER"
#define FROG_BUILD_NUMBER   $BUILD
#define FROG_GIT_COMMITS    $COMMITS
#define FROG_GIT_SHA        "$SHA"
#define FROG_GIT_DIRTY      $DIRTY
#define FROG_GIT_BRANCH     "$BRANCH"
#define FROG_BUILD_DATE     "$STAMP"
#define FROG_VERSION_SHORT  "$SHORT"
#define FROG_VERSION_FULL   "$FULL"
EOF
)

# Only rewrite when something other than the timestamp changed, so an
# unchanged rebuild does not force a recompile.
if [ -f "$OUT" ]; then
	OLD_KEY=$(grep -vE 'FROG_BUILD_DATE|FROG_VERSION_FULL' "$OUT" 2>/dev/null)
	NEW_KEY=$(printf '%s\n' "$NEW" | grep -vE 'FROG_BUILD_DATE|FROG_VERSION_FULL')
	if [ "$OLD_KEY" = "$NEW_KEY" ]; then
		echo "stamp-version: unchanged ($SHORT, build $BUILD)"
		exit 0
	fi
fi

printf '%s\n' "$NEW" > "$OUT"
echo "stamp-version: $SHORT (build $BUILD, $BRANCH, $STAMP)"
